create table if not exists public.fitness_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('workout', 'meal')),
  name text,
  duration integer,
  notes text,
  meal text,
  calories integer,
  goal integer,
  date_key text,
  created_at timestamptz not null default now()
);

alter table public.fitness_entries enable row level security;

create policy "Users can view own fitness entries"
on public.fitness_entries
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own fitness entries"
on public.fitness_entries
for insert
to authenticated
with check (auth.uid() = user_id);

create table if not exists public.security_logs (
  id bigint generated by default as identity primary key,
  email text,
  event_type text not null,
  status text not null,
  detail text,
  ip_address text,
  country text,
  region text,
  city text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.security_logs enable row level security;
