create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  first_name text,
  last_name text,
  age integer,
  current_weight numeric,
  target_weight numeric,
  daily_calorie_goal integer,
  focus text,
  updated_at timestamptz not null default now()
);

alter table public.profiles
add column if not exists first_name text,
add column if not exists last_name text,
add column if not exists age integer;

alter table public.profiles enable row level security;

drop policy if exists "Users can view own profile" on public.profiles;
drop policy if exists "Users can insert own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;

create policy "Users can view own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table if not exists public.fitness_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('workout', 'meal')),
  name text,
  duration integer,
  notes text,
  meal text,
  calories integer,
  goal integer,
  date_key text,
  created_at timestamptz not null default now()
);

alter table public.fitness_entries enable row level security;

drop policy if exists "Users can view own fitness entries" on public.fitness_entries;
drop policy if exists "Users can insert own fitness entries" on public.fitness_entries;
drop policy if exists "Users can update own fitness entries" on public.fitness_entries;
drop policy if exists "Users can delete own fitness entries" on public.fitness_entries;

create policy "Users can view own fitness entries"
on public.fitness_entries
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own fitness entries"
on public.fitness_entries
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update own fitness entries"
on public.fitness_entries
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own fitness entries"
on public.fitness_entries
for delete
to authenticated
using (auth.uid() = user_id);

create table if not exists public.security_logs (
  id bigint generated by default as identity primary key,
  email text,
  event_type text not null,
  status text not null,
  detail text,
  ip_address text,
  country text,
  region text,
  city text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.security_logs enable row level security;
